version: '3.8'

services:
  postgres: 
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=USER
      - POSTGRES_DB=USER
      - DATABASE_HOST=127.0.0.1

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "josue@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "josue"
    ports:
      - "80:80"
    depends_on:
      - postgres
